(function (root) {
  const FACTS = ['enterprise retention is stronger', 'personal users drop during import', 'users who complete import value summaries'];
  const categories = ['funnel_activation', 'segment_retention', 'user_feedback', 'engineering_feasibility'];
  const uid = () => (root.crypto && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
  const event = (sourceStep, actionType, payload) => ({ eventId: uid(), sourceStep, actionType, payload, createdAt: new Date().toISOString() });
  function createTrial(sessionId) { return { sessionId, jobId: 'ai_product', stage: 'first_judgment', selectedEvidence: [], events: [], initial: null, consequence: null, final: null }; }
  function submitFirstJudgment(t, a) { if (!a?.selectedSlice || !Array.isArray(a.deferred) || a.deferred.length !== 2) throw Error('a slice and two deferred options are required'); return { ...t, stage: 'evidence_gathering', initial: a, events: [...t.events, event('first_judgment', 'priority_committed', a), event('first_judgment', 'option_deferred', { deferred: a.deferred })] }; }
  function selectEvidenceCategory(t, id) { const next = [...t.selectedEvidence, id].filter((x, i, all) => all.indexOf(x) === i); if (!categories.includes(id)) throw Error('unknown evidence category'); if (next.length > 2) throw Error('exactly two evidence categories may be selected'); return { ...t, selectedEvidence: next, stage: next.length === 2 ? 'twist' : 'evidence_gathering', events: [...t.events, event('evidence_gathering', 'evidence_categories_selected', { category: id })] }; }
  function revealConsequence(t) { if (t.selectedEvidence.length !== 2) throw Error('select exactly two categories first'); return { ...t, stage: 'reconsideration', consequence: { facts: FACTS, implication: `Review how ${t.initial.selectedSlice} addresses the first-value break.` }, events: [...t.events, event('twist', 'consequence_revealed', { facts: FACTS })] }; }
  function finalizeDecision(t, d) { if (!['retain', 'revise'].includes(d?.mode)) throw Error('mode must be retain or revise'); if (!d.selectedSlice || !d.reason || !d.tradeoff || !d.metric || !d.uncertainty) throw Error('final decision requires reason, tradeoff, metric, and uncertainty'); return { ...t, stage: 'completed', final: d, events: [...t.events, event('reconsideration', d.mode === 'revise' ? 'priority_revised' : 'reconsideration_recorded', d), event('final_decision', 'final_decision_submitted', d)] }; }
  function buildReport(t, interestFeedback) { const ids = (type) => t.events.filter((e) => e.actionType === type).map((e) => e.eventId); return { sections: ['summary', 'requirements', 'profile', 'replay', 'interest', 'unknowns', 'nextMission'].map((id) => ({ id })), taskEvidence: [{ requirementId: 'constrained_prioritization', sourceEventIds: ids('priority_committed'), sourceStep: 'first_judgment', supports: 'May support a bounded product priority under this delivery constraint.', limits: 'Does not prove general product competence or fit.' }, { requirementId: 'evidence_judgment', sourceEventIds: t.events.filter((e) => e.sourceStep === 'evidence_gathering').map((e) => e.eventId), sourceStep: 'evidence_gathering', supports: 'May support selecting supplied signals for this decision.', limits: 'Does not prove broad analytical ability.' }, { requirementId: 'hypothesis_revision', sourceEventIds: t.events.filter((e) => e.actionType.includes('reconsideration') || e.actionType === 'priority_revised').map((e) => e.eventId), sourceStep: 'reconsideration', supports: 'May support retaining or revising after new information.', limits: 'Does not prove stable adaptability.' }, { requirementId: 'testable_next_step', sourceEventIds: ids('final_decision_submitted'), sourceStep: 'final_decision', supports: 'May support naming a bounded validation test and uncertainty.', limits: 'Does not prove outcome prediction.' }], interestFeedback, evidenceReplay: t.events, nextMission: { status: 'Pending', unknown: 'Impact on enterprise retention remains untested.' } }; }
  root.MvuCore = { createTrial, submitFirstJudgment, selectEvidenceCategory, revealConsequence, finalizeDecision, buildReport, FACTS };
})(window);
