(function () {
  const C = window.MvuCore;
  let trial;
  const slices = [{ id: 'simplify_import', label: '简化设置 / 导入' }, { id: 'add_template', label: '增加首次使用模板' }, { id: 'improve_summary', label: '提升总结质量' }];
  const cats = [{ id: 'funnel_activation', label: '漏斗 / 首次使用' }, { id: 'segment_retention', label: '个人 vs 企业留存' }, { id: 'user_feedback', label: '用户反馈' }, { id: 'engineering_feasibility', label: '研发投入 / 可行性' }];
  const esc = (x) => String(x || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const root = () => document.getElementById('mvuRoot');
  function save() { if (trial) localStorage.setItem('wayve-ai-product-trial', JSON.stringify({ trial })); }
  function render(html) { root().innerHTML = `<div class="mvu-card">${html}</div>`; }
  function start(sessionId) { trial = C.createTrial(sessionId || `local-${Date.now()}`); save(); document.querySelectorAll('.screen').forEach((s) => s.classList.remove('active')); document.getElementById('mvu').classList.add('active'); renderJudgment(); }
  function renderJudgment() { render(`<span class="eyebrow">AI PRODUCT · FIRST JUDGMENT</span><h1>选择本周唯一要推进的产品切片</h1><p>注册增长，但首次成功生成偏低，D7 留存下降。研发本周只能交付一项。</p><div class="mvu-options">${slices.map((s) => `<label><input type="radio" name="slice" value="${s.id}"> ${s.label}</label>`).join('')}</div><p>另外两项将被明确延期。</p><button class="btn" id="mvuJudgment">提交临时优先级</button>`); document.getElementById('mvuJudgment').onclick = () => { const selected = document.querySelector('input[name=slice]:checked'); if (!selected) return; const deferred = slices.filter((s) => s.id !== selected.value).map((s) => s.id); trial = C.submitFirstJudgment(trial, { selectedSlice: selected.value, deferred, reason: '基于当前症状先处理首次价值断点。' }); renderEvidence(); }; }
  function renderEvidence() { render(`<span class="eyebrow">EVIDENCE GATHERING · 选择 2 / 4</span><h1>你想先查看哪些信息？</h1><p>未选择的类别在当前阶段保持未检查，不代表能力不足。</p><div class="mvu-options">${cats.map((c) => `<label><input type="checkbox" value="${c.id}"> ${c.label}</label>`).join('')}</div><button class="btn" id="mvuEvidence">查看所选证据</button>`); document.getElementById('mvuEvidence').onclick = () => { const selected = [...document.querySelectorAll('#mvuRoot input:checked')]; if (selected.length !== 2) return; selected.forEach((x) => { trial = C.selectEvidenceCategory(trial, x.value); }); save(); render(`<span class="eyebrow">TWIST · NEW INFORMATION</span><h1>新的事实改变了哪些含义？</h1><ul>${C.FACTS.map((f) => `<li>${esc(f)}</li>`).join('')}</ul><p>事实对所有人相同；它们对你当前承诺的含义需要重新判断。</p><button class="btn" id="mvuReveal">继续到 retain / revise</button>`); document.getElementById('mvuReveal').onclick = () => { trial = C.revealConsequence(trial); save(); renderRevision(); }; }; }
  function renderRevision() { render(`<span class="eyebrow">RECONSIDERATION</span><h1>保留，还是修改你的优先级？</h1><p>${esc(trial.consequence.implication)}</p><div class="mvu-options"><label><input type="radio" name="mode" value="retain"> 保留原决定</label><label><input type="radio" name="mode" value="revise"> 修改为简化设置 / 导入</label></div><label>原因 <textarea id="mvuReason">根据新信息处理首次价值断点。</textarea></label><label>明确取舍 <input id="mvuTradeoff" value="暂缓下游总结优化" /></label><label>验证指标 <input id="mvuMetric" value="首次导入完成率" /></label><label>仍不确定 <input id="mvuUncertainty" value="企业用户的行为是否相同" /></label><button class="btn" id="mvuFinal">提交最终决策</button>`); document.getElementById('mvuFinal').onclick = () => { const mode = document.querySelector('input[name=mode]:checked'); if (!mode) return; trial = C.finalizeDecision(trial, { mode: mode.value, selectedSlice: mode.value === 'retain' ? trial.initial.selectedSlice : 'simplify_import', deferred: trial.initial.deferred, reason: document.getElementById('mvuReason').value, tradeoff: document.getElementById('mvuTradeoff').value, metric: document.getElementById('mvuMetric').value, uncertainty: document.getElementById('mvuUncertainty').value }); save(); renderInterest(); }; }
  function renderInterest() { render(`<span class="eyebrow">INTEREST FEEDBACK</span><h1>这次产品判断工作感觉如何？</h1><div class="mvu-options"><label>投入感 <select id="mvuEngagement"><option>not engaging</option><option selected>somewhat engaging</option><option>very engaging</option></select></label><label>愿意尝试类似任务？ <select id="mvuWillingness"><option>not now</option><option selected>maybe</option><option>yes</option></select></label></div><button class="btn" id="mvuReport">查看探索报告</button>`); document.getElementById('mvuReport').onclick = () => { const report = C.buildReport(trial, { engagement: document.getElementById('mvuEngagement').value, willingness: document.getElementById('mvuWillingness').value }); localStorage.setItem('wayve-ai-product-trial', JSON.stringify({ trial, report })); renderReport(report); }; }
  function renderReport(report) { render(`<span class="eyebrow">EXPLORATION REPORT · AI PRODUCT</span><h1>本次探索报告</h1><h2>Exploration Summary</h2><p>你完成了一次关于 AI meeting assistant 首次价值与留存的产品决策。</p><h2>Role Requirement Profile</h2><p>证据判断、受限优先级、假设修订、可验证下一步。</p><h2>Current Evidence Profile</h2><ul>${report.taskEvidence.map((e) => `<li>${esc(e.supports)} <small>${esc(e.limits).replace(/或适配/g, '或职业判断')}</small></li>`).join('')}</ul><h2>Evidence Replay</h2><ol>${report.evidenceReplay.map((e) => `<li><b>${e.sourceStep}</b> · ${esc(e.actionType)}</li>`).join('')}</ol><h2>Interest Feedback</h2><p>${esc(report.interestFeedback.engagement)} · ${esc(report.interestFeedback.willingness)}</p><h2>Unknowns & Tensions</h2><p>企业与个人用户的后续留存影响仍未验证；未选择的证据类别保持未知。</p><h2>Next Mission</h2><p>${esc(report.nextMission.status)}：${esc(report.nextMission.unknown)}</p><button class="btn" onclick="CareerApp.go('roles')">返回职业探索</button>`); }
  window.MvuUI = { start };
})();
