import { readFile, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const html = await readFile(join(root, 'index.html'), 'utf8');
const app = await readFile(join(root, 'js', 'app.js'), 'utf8');
const assert = (ok, message) => { if (!ok) throw new Error(message); };
['ai_product', 'ai_ui_design', 'ai_ops', 'ai_data_eval', 'ai_app_dev'].forEach((id) => assert(app.includes(`'${id}'`), `missing role ${id}`));
['choice', 'ranking', 'category', 'evidence', 'open', 'analyze2', 'report'].forEach((id) => assert(html.includes(`id="${id}"`), `missing screen ${id}`));
assert((html.match(/data-qnav="prev"/g) || []).length === 5, 'previous control not rendered for every question');
assert((html.match(/data-qnav="next"/g) || []).length === 5, 'next control not rendered for every question');
assert(!html.includes('提交回答') && !html.includes('提交匹配') && !html.includes('提交选择'), 'per-question submit CTA remains');
assert(app.includes('navigateQuestion') && app.includes('persistQuestion') && app.includes('restoreQuestionAnswer'), 'pagination handlers incomplete');
assert(app.includes('questionAnswers') && app.includes('persistedQuestions') && app.includes('quizCompleted'), 'answer persistence/completion state missing');
assert(app.includes('state.questionIndex - 1') && app.includes('state.questionIndex + 1'), 'question boundaries not wired');
assert(app.includes("state.quizCompleted = true") && app.includes("go('analyze2')"), 'final completion does not enter analysis');
assert(app.includes('cross_team_push') && app.includes('跨团队推动') && !app.includes('协作推进'), 'canonical sixth dimension drift');
['适配潜力', '匹配度', 'Career Fit', 'Unified Job Fit', '较适合进入', '跳过动画', 'introSkipBtn', 'preview_only'].forEach((text) => assert(!html.includes(text) && !app.includes(text), `forbidden/stale text: ${text}`));
assert(html.includes('查看其他岗位') && html.includes('返回我的推荐') && app.includes('rolesEntrySource'), 'recommendation navigation regression');
await Promise.all(['assets/report/brand.png', 'assets/profile-avatar.jpg'].map((asset) => access(join(root, asset))));
console.log('FRONTEND SMOKE PASS: question pagination, answer state, completion guard, approved fixes');
