import { readFile, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const html = await readFile(join(root, 'index.html'), 'utf8');
const app = await readFile(join(root, 'js', 'app.js'), 'utf8');
const css = await readFile(join(root, 'css', 'styles.css'), 'utf8');
const assert = (ok, message) => { if (!ok) throw new Error(message); };
['ai_product', 'ai_ui_design', 'ai_ops', 'ai_data_eval', 'ai_app_dev'].forEach((id) => assert(app.includes(`'${id}'`), `missing role ${id}`));
['choice', 'ranking', 'category', 'evidence', 'open', 'analyze2', 'report'].forEach((id) => assert(html.includes(`id="${id}"`), `missing screen ${id}`));
assert((html.match(/data-qnav="prev"/g) || []).length === 5, 'previous control not rendered for every question');
assert((html.match(/data-qnav="next"/g) || []).length === 5, 'next control not rendered for every question');
assert(css.includes('assets/figma/question-arrow-left.svg') && css.includes('assets/figma/question-arrow-right.svg'), 'Figma arrow assets not wired');
assert(css.includes('width:57px') && css.includes('height:57px') && css.includes('gap:23px'), 'Figma pagination geometry drift');
assert(css.includes('border-radius:50%') && css.includes('#a3e092'), 'Figma pagination circle styling drift');
assert(css.includes('.question-arrow:not(:disabled)[data-qnav="next"]') && css.includes('background:#8ac27b'), 'active Next state missing');
assert(css.includes('filter:brightness(0) invert(1)'), 'active Next white arrow state missing');
assert(css.includes('.option:focus-visible') && css.includes('.check-option:has(input:focus-visible)'), 'keyboard focus feedback missing');
assert(css.includes('.figma-question-panel') && css.includes('container-type:inline-size') && css.includes('right:11.05cqw') && css.includes('bottom:2.4919cqw'), 'pagination is not mapped to Figma question panel');
assert(!css.includes('70.764vw') && !css.includes('77vh') && !css.includes('left:70.7638889%'), 'pagination remains root viewport anchored');
assert(css.includes('width:14.84cqw') && css.includes('gap:2.49cqw'), 'pagination group scaling drift');
assert(css.includes('width:41.57%') && css.includes('height:100%'), 'button dimensions are not scaled with panel');
assert(css.includes('.question-arrow { position:relative; display:block;') && css.includes('position:absolute; left:50%; top:50%;') && css.includes('width:27px; height:28px;'), 'Figma arrow is not absolutely centered at source dimensions');
assert(css.includes('width:1698px;') && css.includes('height:866px;') && css.includes('background-size:cover;'), 'laptop artwork fit must preserve the Figma node box with cover');
assert(!/<button[^>]*class="question-arrow"[^>]*>[←→]/.test(html), 'legacy pagination glyph remains in button layout');
assert(!html.includes('提交回答') && !html.includes('提交匹配') && !html.includes('提交选择'), 'per-question submit CTA remains');
assert(app.includes('navigateQuestion') && app.includes('persistQuestion') && app.includes('restoreQuestionAnswer'), 'pagination handlers incomplete');
assert(app.includes('questionAnswers') && app.includes('persistedQuestions') && app.includes('quizCompleted'), 'answer persistence/completion state missing');
assert(app.includes('state.questionIndex - 1') && app.includes('state.questionIndex + 1'), 'question boundaries not wired');
assert(app.includes('data-match-target') && app.includes('connections.clear()'), 'category answer restoration wiring missing');
assert(app.includes("state.quizCompleted = true") && app.includes("go('analyze2')"), 'final completion does not enter analysis');
assert(app.includes('cross_team_push') && app.includes('跨团队推动') && !app.includes('协作推进'), 'canonical sixth dimension drift');
['适配潜力', '匹配度', 'Career Fit', 'Unified Job Fit', '较适合进入', '跳过动画', 'introSkipBtn', 'preview_only'].forEach((text) => assert(!html.includes(text) && !app.includes(text), `forbidden/stale text: ${text}`));
assert(html.includes('查看其他岗位') && html.includes('返回我的推荐') && app.includes('rolesEntrySource'), 'recommendation navigation regression');
await Promise.all(['assets/report/brand.png', 'assets/profile-avatar.jpg'].map((asset) => access(join(root, asset))));
console.log('FRONTEND SMOKE PASS: question pagination, answer state, completion guard, approved fixes');
